### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by thenamelessthing** [gutter2211/couchpotato.provider.bluetigers#1]
Hi @gutter2211 , I want to know how to install the plugin.

I have do a clone git https://github.com/gutter2211/couchpotato.provider.bluetigers.git in the /var/opt/couchpotato/custom_plugins but the Bluetigers doesn't appear in the choice...

**Comment by gutter2211** [comment]
hi,

cd $CouchPotatoServerdir/custom_plugins  # you can find $CouchPotatoServerdir path in settings -> about
git clone https://github.com/gutter2211/couchpotato.provider.bluetigers.git bluetigers

it should works , check your permissions and owner to be sure couchpotato can have acces

**Comment by thenamelessthing** [comment]
thanks you! It solved the problem.  The problem was caused by the missing bluetigers folder destination at the end of the git clone command.

**Comment by gutter2211** [comment]
good news.
i will update README with this info

**Comment by thenamelessthing** [comment]
@gutter2211 I'm not familiar with git and how do you suggest to update the plugin? (ex: in a cron job)

Simply something like:

`#!/bin/bash

rm -r /var/opt/couchpotato/custom_plugins/bluetigers && git clone https://github.com/gutter2211/couchpotato.provider.bluetigers.git bluetigers`

Or we can do it with the git command directly?

**Comment by gutter2211** [comment]
cd bluetigers
git pull

don't need to remove to clone again.

after to have a automatic update it's not really necessary , i'm not plan to  update often the code
