### ISSUE TITLE
result not found..

### ISSUE THREAD

**Issue by thenamelessthing** [gutter2211/couchpotato.provider.bluetigers#2]
Hi, I don't know why. But when I search for "the secret life of pets" no result are accepted.

For the logs:

http://cryptb.in/iJ#a656ef60dbed8be1211186daafd07a78

My words requirement:

http://screencloud.net/v/tBq8

My quality requirement:

http://screencloud.net/v/m921

If I manually search un BT here his the result:
(you can see it must at least find: The.Secret.Life.of.Pets.2016.MULTI.1080p.3D.BluRay.SBS.x264.ACOOL)
http://screencloud.net/v/F3pW

**Comment by gutter2211** [comment]
hi,

i know this issue , i have the same.
it's because plugins take movie title and find french movie title and to search with it.

i need to add a fallback when no result with french movie title .

**Comment by thenamelessthing** [comment]
ohh!  I'm not crazy! I'm not alone!  Yeah..   Any plan to fix this soon?

**Comment by gutter2211** [comment]
i'm on i hope fix it after end of week if i have time

**Comment by gutter2211** [comment]
workaround are committed

**Comment by thenamelessthing** [comment]
Je ne sais pas si cela peut t'aider: Concernant la recherche, couchpotato lance toujours par défaut une requête en langue anglaise. Ensuite seulement d'autres requêtes suivent en fonction des langues additionnelles ajoutées au travers la propriété languages. Enfin couchpotato aggrège les différents résultats. Il n'est donc pas nécessaire d'ajouter la langue anglaise au paramètre languages, couchpotato s'en charge déjà.

A noter que souvent la requête anglaise permet de récupérer un titre français, mais cela n'étant pas toujours le cas, le fait d'ajouter la propriété languages = fr nous en assure systématiquement.

I can translate if necessary..

**Comment by gutter2211** [comment]
i'm french :)

in your case bluetigers have some times Movies with English title and sometimes with French Title.
modification i do is to do first search with title give by CP and if no result do search with french title .

you don't have all the times the french title in the list of title in CP
