### ISSUE TITLE
Bluetigers Closed!

### ISSUE THREAD

**Issue by thenamelessthing** [gutter2211/couchpotato.provider.bluetigers#3]
Hi!  Bad news today. BT tracker are now closed!

Maybe you can create new plugins for another tracker?

**Comment by thenamelessthing** [comment]
![image](https://cloud.githubusercontent.com/assets/10235448/20456619/42e72d06-ae48-11e6-948d-5f74f495a2ad.png)

**Comment by gutter2211** [comment]
hi,
bad news :(

i'm not on a other private tracker so for the moment no .
if you know some tracker to replace bluetigers i'm opened

**Comment by thenamelessthing** [comment]
your email?

**Comment by gutter2211** [comment]
guil50 at free.fr
